### ISSUE TITLE
Using ES6

### ISSUE THREAD

**Issue by JonKrone** [travel-consensus/travel-consensus#25]
What do you guys think about writing with some ES6?

my considerations:
- Good time to learn and practice!
- ES6 has a number of actually helpful features.
- Would make our code a little less consistent because of varying comfort levels and style preferences with ES6.
- Some code might be hard to read if you don't understand the new syntax or feature.
  - we could heavily comment / have it explained by the person who wrote it
- Babel can translate ES6 to ES5
  - Good for bringing it to the browser
  - Bad because the new code Babel generates is sometimes even harder to understand

**Comment by amberleyromo** [comment]
I have not really touched ES6 at all yet, so I would find that an added learning curve -- which generally is good, but because of the time frame I personally think we have enough on our plate without adding more considerations.
