### ISSUE TITLE
Implement removal via server

### ISSUE THREAD

**Issue by JonKrone** [travel-consensus/travel-consensus#51]
We should be able to remove..:
- tasks from a trip
- users from a trip
- suggestions from a task
- etc?

@prozack

**Comment by prozack** [comment]
Would we need a method to remove from the database?  Or could we just hide those entries in the results when searching?

**Comment by JonKrone** [comment]
Sorry zack, I didn't know about your comment. Do you know how I can get setup to be notified about these?

I think removing would be the way to go so that other users who are viewing the same page don't also see it. So we'd need to accept DELETE requests that then remove from the database.

**Comment by prozack** [comment]
I added some methods to deleted from various db based on criteria.  If foreign keys need to erased, also wrote those methods in for user, task, trip, suggestion, and message. @JonKrone
